version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "17254:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: