version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "17254:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysql:/var/lib/mysql
  redis:
    container_name: redis
    image: bitnami/redis:7.4.2
    ports:
      - "16697:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=password
      - REDIS_PORT_NUMBER=6379
      - REDIS_IO_THREADS_DO_READS=yes

volumes:
  mysql: