name: Dev Deploy to NCP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.DEV_APPLICATION_YML }}" | base64 --decode > src/main/resources/application-dev.yml
          echo "${{ secrets.SOCIAL_APPLICATION_YML }}" | base64 --decode > src/main/resources/application-social.yml
          echo "${{ secrets.NCP_APPLICATION_YML }}" | base64 --decode > src/main/resources/application-ncp.yml
          find src
          rm src/main/resources/application-local.yml
          rm src/main/resources/application-test.yml

      - name: Set AuthKey
        run: |
          mkdir -p src/main/resources/static
          echo "${{ secrets.AUTH_KEY }}" > src/main/resources/static/AuthKey.p8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Set Date
        run: |
          echo "date=$(TZ=Asia/Seoul date +'%y%m%d')" >> $GITHUB_ENV
      - id: commit-hash
        uses: prompt/actions-commit-hash@v3

      - name: Login to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: near.kr.ncr.ntruss.com
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build, tag, and push image to NCP Container registry
        id: build-image
        env:
          DOCKER_REGISTRY_URL: near.kr.ncr.ntruss.com
          REPOSITORY_NAME: near-io-kr-dev
          IMAGE_TAG: ${{ format('{0}-{1}', env.date, steps.commit-hash.outputs.short) }}
        run: |
          docker build -t $DOCKER_REGISTRY_URL/$REPOSITORY_NAME:$IMAGE_TAG -f ./Dockerfiles/Dockerfile-dev  .
          docker image tag $DOCKER_REGISTRY_URL/$REPOSITORY_NAME:$IMAGE_TAG $DOCKER_REGISTRY_URL/$REPOSITORY_NAME:latest
          docker push $DOCKER_REGISTRY_URL/$REPOSITORY_NAME:$IMAGE_TAG
          docker push $DOCKER_REGISTRY_URL/$REPOSITORY_NAME:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_DEV_IP }}
          username: root
          password: ${{ secrets.NCP_DEV_PASSWORD }}
          script: |
            ./start.sh
            docker compose down
            docker compose pull
            docker compose up -d
